name: condaenv
channels:
  - conda-forge
dependencies:
  - joblib=1.2.0
  - loguru=0.6.0
  - numpy=1.23.3
  - pandas=1.4.4
  - pytest=7.1.3
  - pytorch-cpu=1.12.1
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - tqdm=4.64.1

  - pip:
      - flwr[simulation]==1.1.0
